name: Test Docker Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REPLACE_CHINA_MIRROR: false
        VCS_REF: ${{ github.sha }}
        BUILD_DATE: ${{ steps.date.outputs.date }}
        TAG: pr-test
      with:
        name: tryzealot/zealot:${{ env.TAG }}
        no_push: true
        buildargs: BUILD_DATE,VCS_REF,TAG,REPLACE_CHINA_MIRROR